// Code generated by https://github.com/expgo/ag DO NOT EDIT.
// Plugins:
//   - github.com/expgo/factory/annotation

package example

import (
	"github.com/expgo/factory"
)

func init() {
	factory.Factory[Interface](Create)
}
