// Code generated by https://github.com/expgo/ag DO NOT EDIT.
// Plugins:
//   - github.com/expgo/factory/annotation

package example

import (
	"github.com/expgo/factory"
)

func init() {
	factory.Factory[StructInterface](factory.New[MyStructFactory]()).MethodName("New1").Params("self").CheckValid()
	factory.Factory[FuncInterface](newMyInterface).Params("self").CheckValid()
}
