// Code generated by https://github.com/expgo/ag DO NOT EDIT.
// Plugins:
//   - github.com/expgo/factory/annotation

package example

import (
	"github.com/expgo/factory"
)

var (
	__LocalVarMyStruct = factory.Singleton[LocalVarMyStruct]().InitParams("aaa", "bbb")
)

func init() {
	factory.Singleton[MyStruct]().InitParams("aaa", "bbb")
}
